### ISSUE TITLE
Moving over from Catalina & Clover

### ISSUE THREAD

**Issue by hellojere** [baughmann/designaire-z390-intel-i9-9900k-opencore#18]
Thanks for the great work on this. This is really not an issue per se, but as there are no GitHub Discussions enabled on the repo, hope questions here are ok too. 

I'm currently on Catalina 10.15.0 with a Clover based EFI (Morgonaut's) on exactly the same build as you, and I'm looking to make the move to OpenCore and Big Sur. 

As the latest version is not recommended for Catalina, I'm not quite sure in which order to proceed with the upgrade. Do you think the latest EFI will boot enough to get through the update process? Or should I do the upgrade first and get the EFI replaced afterwards? 

I do have full copies of the hard drive to test things out first but thought to ask beforehand.

Any guidance highly appreciated.

**Comment by baughmann** [comment]
Hmm well you’ve got a couple of options as I see it.

1. Go through the commit history on this repo and download the EFI as it was just before the Big Sur upgrade, use that during the macOS update process, and then use the current EFI once the update has been installed and you’re trying to boot to Big Sur.

2. (Recommended) Since you have backups (assuming you have time machine backups too), and you’re coming from Clover, it’s really best to do a clean install. Clover is messy and directly switching isn’t always smooth.
    - Use [gibMacOS](https://github.com/corpnewt/gibMacOS) to download the Big Sur install files
    - Use create a bootable USB with the installation files
    - place my latest EFI on the USBs EFI partition
    - install Big Sur fresh

**Comment by hellojere** [comment]
@baughmann Thank you. Certainly going with a clean install then, plenty of bootable drives to test it out with beforehand as well.

**Comment by baughmann** [comment]
@hellojere sounds good, let me know how it goes. Best of luck.
