### ISSUE TITLE
Sidecar does not work without first enabling iGPU in BIOS

### ISSUE THREAD

**Issue by QueercoreTrash** [baughmann/designaire-z390-intel-i9-9900k-opencore#19]
Not necessarily a bug but in the documentation as it stands, people are encouraged to switch off iGPU, however as this machine is using iMac19,1 it expects iGPU to provide Sidecar (iPad as extra screen when connected via cable - in my case a Thunderbolt Port to the USB C of the Motherboard)

I have not upgraded to Big Sur yet so iGPU being Disabled may impact Sidecar in the same manner.

Solution: Boot into BIOS, change IGPU (Under Peripherals tab) and set explicitly to ENABLED
Currently using Z390DESI.F9i

**Comment by baughmann** [comment]
Good point. I’ll give this a try myself and change the docs. Thank you

**Comment by baughmann** [comment]
Verified that it works with no changes to the EFI. Have not been able to verify Sidecar works on Big Sur because I don't have an iPad. Let me know if it works once you upgrade, @QueercoreTrash 

I also added a [BIOS guide](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/master/BIOS.md) and mentioned the fix you suggested there.

Thanks for the input!
