### ISSUE TITLE
Almost success with your EFI Folder

### ISSUE THREAD

**Issue by riyas1980** [baughmann/designaire-z390-intel-i9-9900k-opencore#33]
Hi Baughmann,

Finally, I've managed to install Big Sur 11.1. Everything is working fine. Except for Fenvi T919. It was working. But Suddenly my PC wasn't booting at all (Not even Bios). The PC was shutting down immediately. After almost 2 days, I've found the culprit. It's the wifi card. Once I removed it, everything is fine. I've changed the port but the issue was still there. So I've decided to remove Fenvi card and use only Ethernet.

I just want to know what I need to remove in config.plist to cleanup the section regarding this wifi card. Because I still have the wifi symbol at the top right eventhough the card was removed.

Thanks for your help. And thanks again for EFI Folder

Kind Regards

**Comment by baughmann** [comment]
You're likely still seeing the wifi Icon because of the integrated BT/WiFi on the mobo. WiFi will work OK on the integrated chip, but BT will not. You can disable the integrated chip in the BIOS if you no longer want to use it.

As of Big Sur I'm no longer using any AirportBrcm kexts IIRC, so you should not have to remove anything there.

I would suggest returning your Fenvi and getting another one. Also, if your CPU cooler uses the USB header on the motherboard (most nice ones do), then you will need to get an internal USB hub like I did, otherwise your PC will have issues because the cooler will not function correctly (i.e. the PC will shut down after a little while of running).

**Comment by riyas1980** [comment]
Thanks Baughmann for your reply. Actually Wifi and Bluetooth is working fine with itwlm and two other kexts. The complete procedure is here : https://www.youtube.com/watch?v=no_XkR_LLNc

**Comment by baughmann** [comment]
Ahh I’ve been keeping an eye on that kext as it develops, seems like an interesting idea.

**Comment by baughmann** [comment]
So we’re all good then? Can I close this?

**Comment by riyas1980** [comment]
Yes thanks again for your help. You can close it.
