### ISSUE TITLE
Error message that seems random and without ill effect

### ISSUE THREAD

**Issue by jahwookie** [baughmann/designaire-z390-intel-i9-9900k-opencore#35]
Actually everything is running very well in Big Sur land. Since plugging in the newest EFI, however, I noticed during log-in, just above the Aorus logo, some copy that comes and goes too quickly to read. Finally got curious enough to put my phone in video mode and record the transition so I could freeze frame it after. 

Message reads: OCS: Failed to calculate size of false field containing <empty> as type integer, context PlayChime 

Any idea what the system is on about here? Is it something I should attend to? Thanks & happy holidays!

**Comment by baughmann** [comment]
Sorry @jahwookie I thought I had already gotten back to you. Yeah, I've seen that as well. Normally that's just a warning that something in the `config.plist` is not quite right, but I haven't gotten around to looking at it since it doesn't really affect performance at all.

I will get to it eventually, but if you want to figure out where in the `config.plist` is causing this and make a merge request, i'd be happy to accept :)

**Comment by jahwookie** [comment]
No, that's all right. You can close this (if it's open). Might be a
learning experience for me to do that snipe hunt. Have a happy new year!

**Comment by baughmann** [comment]
I'll keep it open as a reminder for myself, no worries.

**Comment by jahwookie** [comment]
Great. I'll let you know if I discover anything, though you'll probably
beat me to it!

**Comment by jahwookie** [comment]
Something a search took me to on Reddit. Maybe related?


I just had to fix this and it's in my head so here's some details....

config.plist/uefi/audio/playchime

boolean to string

acceptables values: Auto, Enabled, Disabled

auto basically enables the chime if nvram is missing the startup mute
variable, the others are unconditional

**Comment by baughmann** [comment]
Well, looks like this is an easy fix then! Thanks for digging into this.

**Comment by baughmann** [comment]
@jahwookie Happy to say I finally fixed this :) Closing
