### ISSUE TITLE
Include driver for Intel 211 Gigabit Ethernet Adapter

### ISSUE THREAD

**Issue by schreiberstein** [baughmann/designaire-z390-intel-i9-9900k-opencore#6]
Hello!

If you would include the following kernel extension, the Intel 211 Gigabit Ethernet adapter (first port) would be fully functional.
Tested on : macOS Big Sur Public Beta 1

https://github.com/khronokernel/SmallTree-I211-AT-patch

Cheers,
schreiberstein

**Comment by baughmann** [comment]
@schreiberstein If you're familiar with Git, feel free to make a pull request and I will happily test and merge. Otherwise, I will go ahead and give that a test once I've completed testing the BIOS beta update you mentioned in the [other thread](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/issues/4) :)

**Comment by schreiberstein** [comment]
#7 

Here you go. Hope it is alright.
Cheers,
schreiberstein

**Comment by baughmann** [comment]
@schreiberstein Yeah, will test it as soon as I get my BIOS working again haha.

**Comment by baughmann** [comment]
Your PR has been merged 👍
